In [ ]:
# Q1. Explain the concept of R-squared in linear regression models. How is it calculated, and what does it
# represent?
Ans.
R-squared, often denoted as R², is a measure that indicates the proportion of the variance in the dependent 
variable (the outcome) explained by the independent variable(s) in a linear regression model.

Formula of R-Squared is:
    1 - Sum of square resuidual/Sum of total square

In [3]:
import pandas as pd 
df = pd.read_csv('height-weight.csv')
df.head()

Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [4]:
df.shape

(23, 2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  23 non-null     int64
 1   Height  23 non-null     int64
dtypes: int64(2)
memory usage: 496.0 bytes


In [6]:
df.isnull().sum()

Weight    0
Height    0
dtype: int64

In [10]:
df[df.duplicated()]

Weight  Height
11      95     182

In [15]:
df_drop_duplicate = df.drop(df.index[11])

In [17]:
df_drop_duplicate.head()

Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [48]:
# Independent and dependent variable 
X = df[['Weight']]
y = df['Height']

In [49]:
X.shape,y.shape

((23, 1), (23,))

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [52]:
X_train_sclaed = scaler.fit_transform(X_train)
X_train_sclaed

array([[ 0.41007671],
       [-1.51215787],
       [ 1.49934297],
       [-1.70438132],
       [-0.74326404],
       [-0.10251918],
       [ 0.28192774],
       [-1.3840089 ],
       [-0.99956198],
       [ 0.02562979],
       [ 1.17897054],
       [ 0.66637465],
       [ 0.85859811],
       [ 0.98674708],
       [ 0.53822568]])

In [53]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[ 0.41007671],
       [ 0.41007671],
       [-1.70438132],
       [ 1.49934297],
       [-0.42289161],
       [ 2.14008783],
       [-0.87141301],
       [ 1.8197154 ]])

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
lr = LinearRegression()
lr.fit(X_train_sclaed,y_train)

LinearRegression()

In [56]:
import warnings
warnings.filterwarnings('ignore')
y_pred = lr.predict(X_test_scaled)
y_pred

array([162.8051967 , 162.8051967 , 128.40340121, 180.52733377,
       149.25297424, 190.95212028, 141.95562368, 185.73972703])

In [59]:
# Here I will perform r2 square
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred)
score

0.8074173081896224

In [ ]:
# Q2. Define adjusted R-squared and explain how it differs from the regular R-squared.
Ans.
Adjusted R-squared is like a smarter version of regular R-squared. While regular R-squared measures how well
your model fits the data, adjusted R-squared considers the number of predictors in your model. It penalizes 
you if you add useless predictors that don't really improve your model. So, adjusted R-squared gives a more
realistic picture of how effective your predictors are, helping you avoid the trap of thinking your model is
better just because you added more variables.

In [ ]:
# Q3. When is it more appropriate to use adjusted R-squared?
Ans.
Adjusted R-squared is more appropriate when you're comparing models with different numbers of predictors. It 
helps you see if adding more predictors is genuinely improving your model or if it's just making it look 
better without adding real value.

In [ ]:
# Q4. What are RMSE, MSE, and MAE in the context of regression analysis? How are these metrics
# calculated, and what do they represent?
Ans.
1. Mean Squared Error (MSE):
MSE is calculated by taking the average of the squared differences between the actual and predicted values. It
penalizes large errors more heavily than small ones. The squared differences help in emphasizing and amplifying
larger errors.

Root Mean Squared Error (RMSE):
RMSE is the square root of the MSE. It gives an error metric in the same unit as the dependent variable. RMSE is
a more interpretable metric than MSE because it is on the same scale as the target variable. It provides a measure
of how well the model is expected to perform in predicting the actual values.

Mean Absolute Error (MAE):
MAE is the average of the absolute differences between the actual and predicted values.MAE is less sensitive to 
outliers than MSE because it does not involve squaring. It gives an average of the absolute errors, providing a 
straightforward interpretation of the average magnitude of errors.

In [64]:
# Here I am calculated all the metrics on the behalf of previous Q1.
import numpy as np
from sklearn.metrics import mean_squared_error,mean_absolute_error
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mse)
print('Mean_Squared_Error :',mse)
print('Mean_Absolute_Error :',mae)
print('Root_Mean_Squared_Error',rmse)

Mean_Squared_Error : 91.42562383241722
Mean_Absolute_Error : 8.332521348806658
Root_Mean_Squared_Error 9.561674739940552


In [ ]:
# Q5. Discuss the advantages and disadvantages of using RMSE, MSE, and MAE as evaluation metrics in
# regression analysis.
Ans.
Advantages and Disadvantages of RMSE, MSE, and MAE in Regression Analysis:

1. Mean Squared Error (MSE):
Advantages:
MSE gives higher weight to larger errors, which can be beneficial if you want to strongly penalize 
significant deviations.
It is differentiable, making it suitable for optimization algorithms.

Disadvantages:
The squared nature of MSE can amplify the impact of outliers, making the metric sensitive to extreme
values.
The unit of MSE is not the same as the target variable, which can make interpretation challenging.

2. Root Mean Squared Error (RMSE):
Advantages:
RMSE is on the same scale as the dependent variable, providing a more interpretable measure of prediction
error.
It retains the emphasis on larger errors introduced by MSE.

Disadvantages:
Similar to MSE, RMSE is sensitive to outliers, and the squared nature can magnify their influence.
It might not be suitable for all scenarios, especially when the goal is to reduce the impact of extreme values.

3. Mean Absolute Error (MAE):
Advantages:
MAE is less sensitive to outliers since it uses absolute differences rather than squared differences.
It provides a straightforward interpretation as the average magnitude of errors.
The unit of MAE is the same as the target variable, facilitating easier understanding.

Disadvantages:
MAE does not penalize larger errors as heavily as MSE or RMSE, which might be a drawback if you want to emphasize
the significance of larger deviations.
The non-differentiability of the absolute function can be a limitation in certain optimization scenarios.

In [ ]:
# Q6. Explain the concept of Lasso regularization. How does it differ from Ridge regularization, and when is
# it more appropriate to use?
Ans.
Lasso regularization is like a coach for your regression model, encouraging it to be more efficient. It adds a penalty
term to the traditional regression, pushing some of the less important features to have exactly zero coefficients. It's
a way to simplify your model and select only the most essential predictors.

Now, compared to its teammate Ridge regularization, Lasso is more ruthless. While both push for simplicity, Lasso can 
outright kick out variables by setting their coefficients to zero, unlike Ridge, which only shrinks them.

So, when to use Lasso? Think of it as a hero when you suspect that some of your features are not that crucial and can be
dropped from the team. If you want a sparse and straightforward model, Lasso might be your go-to regularization method.

In [ ]:
# Q7. How do regularized linear models help to prevent overfitting in machine learning? Provide an
# example to illustrate.
Ans.
Regularized linear models act like a coach guiding your model to avoid showing off too much. They add a penalty for 
complexity, preventing it from memorizing the training data too well, which can lead to overfitting. For example, imagine
teaching a model to predict a student's grades. Without regularization, it might try too hard to fit the exact scores of 
each student in the training class, even the noisy ones. Regularization steps in like a sensible coach, saying, "Okay, 
don't get too obsessed with these specific scores. Focus on the important patterns, and avoid trying to impress every single
student's result.

In [ ]:
# Q8. Discuss the limitations of regularized linear models and explain why they may not always be the best
# choice for regression analysis.
Ans.
Regularized linear models, while helpful, have their limits. They might not always be the Most important for regression
analysis because:
1. Loss of Important Features:
Regularization can be too strict, kicking out variables, even important ones, by setting their coefficients to zero. This
can lead to oversimplification and loss of valuable information.

2. Model Complexity:
These models might struggle with highly complex relationships in the data. If the underlying patterns are intricate, overly
simplifying the model through regularization might not capture the nuances well.

3. Parameter Sensitivity:
The performance of regularized models depends on choosing the right regularization strength. Picking a value too high or too 
low can impact results. It's like finding the Goldilocks zone – not too much, not too little.

4. Assumption of Linearity:
Regularized linear models assume that relationships between variables are linear. If your data involves more complex, non-
linear connections, these models might not be the best fit.

In [ ]:
# Q9. You are comparing the performance of two regression models using different evaluation metrics.
# Model A has an RMSE of 10, while Model B has an MAE of 8. Which model would you choose as the better
# performer, and why? Are there any limitations to your choice of metric?
Ans.
RMSE of 10 (Model A): This metric penalizes larger errors more heavily due to the squared nature of the calculation. If
minimizing large errors is crucial for my application, Model A might be preferable.

MAE of 8 (Model B): This metric is less sensitive to outliers as it considers absolute differences. If prioritize a
metric that gives equal weight to all errors, regardless of size, Model B could be a better choice.

Absolutely! The choice of metric, whether it's RMSE or MAE, has its limitations. For example:
1. Sensitivity to Outliers: Both metrics can be influenced by outliers, but in different ways. RMSE is more sensitive
to large errors because it squares them, while MAE treats all errors equally.
2. Scale Differences: RMSE and MAE are in different units than the original data. While RMSE is in the squared unit,
MAE is in the original unit. This can affect how you interpret and communicate the results.
3. Problem-specific Considerations: The "best" metric depends on the specific problem. Sometimes, what makes sense for 
one situation might not be suitable for another. Always consider the characteristics of your data and the goals of your 
analysis.
4. Model Interpretability: RMSE might be less intuitive to interpret compared to MAE, especially for non-technical
audiences. It's crucial to choose a metric that aligns with how you want to communicate the performance of your model.

In [ ]:
# Q10. You are comparing the performance of two regularized linear models using different types of
# regularization. Model A uses Ridge regularization with a regularization parameter of 0.1, while Model B
# uses Lasso regularization with a regularization parameter of 0.5. Which model would you choose as the
# better performer, and why? Are there any trade-offs or limitations to your choice of regularization
# method?
Ans.
Ridge (Model A, λ=0.1): Ridge is like a moderate coach, gently pushing the model to be efficient without completely
kicking out features. It's good when we want to avoid overemphasizing any single variable and maintain most of our features.

Lasso (Model B, λ=0.5): Lasso is a bit more ruthless. It not only encourages simplicity but might kick out less essential 
features by setting their coefficients to zero. It's handy when we suspect that some features aren't that crucial.

Trade-offs and Considerations:
1. Sparsity of Features: If having fewer, more essential features is crucial, Lasso (Model B) might be preferred due to its
tendency to set some coefficients to zero.
2. Variable Importance: Ridge (Model A) is gentler on features, so if we believe many variables are important to our outcome,
Ridge could be better.
3. Ridge for Multicollinearity: If our features are highly correlated (multicollinearity), Ridge is often more stable. Lasso 
might arbitrarily choose one of the correlated features and ignore the rest.
4. Choice of Regularization Strength : The performance of both models heavily depends on choosing the right regularization
strength. Too high or too low values might not yield optimal results.